### ISSUE TITLE
CORS issue observed with updated SciDuct

### ISSUE THREAD

**Issue by Annapurna-Kupast** [NSSAC/CINES#136]
CORS issue was being observed for File Service on 1 March. On reporting the issue to Dustin - he fixed it for File Service.

On 2 Mar - the CORS issue was seen for Job Listing. Please see attached screenshot. 

Assigning this ticket to Dustin and Persistent team to track the observations to closure
![CORS_Job_Listing](https://user-images.githubusercontent.com/49201308/109614397-99a50780-7b58-11eb-90f9-8fe1528ebbd8.JPG)

**Comment by Abhishek001005** [comment]
@dmachi 
While testing the application we have observed the CORS issue for the following functionality.
1. If  any loggedin user tries to upload the file  ('https://sciduct.bii.virginia.edu/fs/file//home/Manvitha/').
2. While creating the dynamic form for the snap methods.

We have also observed that after uploading the file the update_date  which we are getting  in file manager listing page is not correct . Every time it is  showing updated as 6hours ago for the file which is just uploaded.

If required we can discuss this on EXCEADS call tomorrow of 8.30 am. It would be okay if you join by 9 am'.

**Comment by dmachi** [comment]
1.  That url is likely to fail because it has // in the url. What is the error, just CORS?  I would really like to be able to test this stuff, what branch do I need to use or merge to reproduce?
2. What do you mean by the second.  Do you mean that you get a CORS error when you try to fetch JS/job_definition/<some def> ?

The update_date should be in UTC and would need to be localized, so I suspect thats what you are seeing there.

**Comment by Abhishek001005** [comment]
@dmachi 
1 . Yes it is just CORS error while uploading the file , you can clone the code from  "master_updated_jobDefinition"  branch for testing purpose.
2 . While fetching the  metadata of Job definition.
   URL: https://sciduct.bii.virginia.edu/jobsvc/job_definition/{jobDefinationName}

**Comment by dmachi** [comment]
I believe the CORs issues are resolved.  Please let me know if you see any more.  I was able to see and upload files.   I was also able to retrieve the job definition object ( can see it in the network panel), though if I go to net.science/snap_GenRndGnm, I get the form under construction method still.

**Comment by Abhishek001005** [comment]
@dmachi 
1. We are able to fetch the Job definition object but with the file upload functionality while uploading the file which is already existing in file manager list , we are still facing the CORS issue. 
2. Per changes in the input schema, for new SciDuct, I have done minor changes on the application side, which now renders the forms correctly. Please take a pull and check.

**Comment by dmachi** [comment]
Turns out the server was returning the error correctly but nginx doesn't put headers on to error responses by default.  I've changed that and the upload with a conflict error responds correctly in the browser.

**Comment by murli1201** [comment]
Editing user meta is showing a CORS error.
![ScreenHunter_23 Mar  06 18 08](https://user-images.githubusercontent.com/54397265/110207567-5cb77880-7eaa-11eb-8fbc-9afb96ff9bea.png)

**Comment by dmachi** [comment]
I’m not exactly sure why this is showing up as a CORS error for you, it was just a normal 400 error for me.   All of the file types in the fileservice end up populating an enum in the file schema.  In this case the query for those files types was only returning the first 25 records, so some of the types weren’t available in that enum so validation of these updates failed when it tried to store the updated metadata.  I have fixed that issue now.  Can you please try this again and see if it is working for you now?

**Comment by murli1201** [comment]
I tried editing the usermeta now, and it was edited successfully without any errors.
Thank you.

**Comment by murli1201** [comment]
The PATCH API used for Editing user meta is again showing a CORS error.
![Screenshot (53)](https://user-images.githubusercontent.com/54397265/113129730-de47bf80-9238-11eb-85ab-7bb16ddbeb00.png)

**Comment by dmachi** [comment]
Hi Murli,

I’m not able to reproduce this locally.  Can you be more specific on what you are patching and what is in the patch request?

Thanks,
Dustin

**Comment by dmachi** [comment]
Right.  What was the specific file you tried to edit and what was the patch content.  I just did the edit from the net.science UI and it worked, though my version of the UI is a few weeks old (I haven’t pulled your changes in for a couple of weeks).   I will try to pull in your changes and see if I get this error now.

**Comment by murli1201** [comment]
I checked it for various files. When we had the CORS extension ON in the browser we got this error. If we turn it off, it gives no error and the usermeta is edited successfully.

Should the extension matter ? ON or OFF?

**Comment by dmachi** [comment]
I’ve never used an extension for CORS.  I just looked at https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en <https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en> and it looks like it probably intercepts the requests and adds CORS headers for sites that don’t use them….perhaps it doesn’t add PATCH as an allowed method, I’m not sure.
